### ISSUE TITLE
Callouts doesn't work with customTheme for PDF

### ISSUE THREAD

**Issue by opensource21** [rdmueller/docToolchain#31]
If I use 
```
        'pdf-stylesdir': 'pdfTheme',
            'pdf-style': 'custom',
```
I get the following errors:
```
The following text could not be fully converted to the Windows-1252 character set:
| ?
(ArgumentError) uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.15/data/fonts/OpenSansEmoji.ttf not found
:generatePDF FAILED
```
It looks like the font must be adjusted, but I'm unsure how.

See https://github.com/asciidoctor/asciidoctorj/issues/389 and https://github.com/asciidoctor/asciidoctor-pdf/issues/409

**Comment by rdmueller** [comment]
Thanx - I had this error message once before. I am sure I can fix it during the weekend...

**Comment by rdmueller** [comment]
So, the problem seems to be related to this file:

https://github.com/rdmueller/docToolchain/blob/master/src/docs/pdfTheme/custom-theme.yml

At least, this file defines the fonts used for the PDF rendering.

I removed the fallback to emoji font and the reference to this font at all - it seems they are not embedded in the pdf plugin.

This renders at least the callouts within the normal text, but not in the mono-space text :-(

As far as I know, only certain fonts are embedded within the pdf-plugin. And I have the feeling that is it still in alpha because of these problems - no monospaced font with callouts.

A solution could be to reference another font from within the above mentioned file

**Comment by rdmueller** [comment]
the PDF style guide also seems not to solve this problem:

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-callout-numbers

The setting

```
conum:
  font_family: M+ 1mn
  font_color: #ff2146
```

Displays the callouts (also the monospaced once) in red, but still with the wrong character.

The following older issue also explains some of the problems but does not lead to a solution:

https://github.com/asciidoctor/asciidoctor-pdf/issues/31

**Comment by opensource21** [comment]
Well the missing fonts are indeed the problem. I would recommend to add the fonts to the repo to get a stable behavior, see [customfonts](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#custom-fonts) and set the `pdf-fontsdir`. If you remove the custom pdf-style everything works fine.

**Comment by rdmueller** [comment]
so, if everything works find without the custom pdf-style, this means the style is wrong and the plugin contains a working font... I think I will investigate on this...

**Comment by rdmueller** [comment]
I think I found it... can you please give it a try?

**Comment by opensource21** [comment]
Now it's fixed
